import React, { createContext, useContext, useState, useEffect } from 'react';

/**
 * 22 Official Languages supported by GrainWise AI
 */
export const SUPPORTED_LANGUAGES = [
  { code: 'English', name: 'English', native: 'English' },
  { code: 'Hindi', name: 'Hindi', native: 'हिंदी' },
  { code: 'Tamil', name: 'Tamil', native: 'தமிழ்' },
  { code: 'Telugu', name: 'Telugu', native: 'తెలుగు' },
  { code: 'Punjabi', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'Marathi', name: 'Marathi', native: 'मराठी' },
  { code: 'Bengali', name: 'Bengali', native: 'বাংলা' },
  { code: 'Gujarati', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'Kannada', name: 'Kannada', native: 'કન્નડ' },
  { code: 'Malayalam', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'Odia', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'Assamese', name: 'Assamese', native: 'অসমীয়া' },
  { code: 'Urdu', name: 'Urdu', native: 'اردو' },
  { code: 'Maithili', name: 'Maithili', native: 'मैथिली' },
  { code: 'Santali', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'Kashmiri', name: 'Kashmiri', native: 'كأشُر' },
  { code: 'Nepali', name: 'Nepali', native: 'नेपाली' },
  { code: 'Konkani', name: 'Konkani', native: 'कोंकणी' },
  { code: 'Sindhi', name: 'Sindhi', native: 'سنڌي' },
  { code: 'Dogri', name: 'Dogri', native: 'डोगरी' },
  { code: 'Manipuri', name: 'Manipuri', native: 'মৈতৈলোন্' },
  { code: 'Sanskrit', name: 'Sanskrit', native: 'संस्कृतम्' }
];

/**
 * Translation Dictionary for all 22 languages
 */
export const TRANSLATIONS = {
  English: {
    nav_features: "Features",
    nav_ai_scan: "AI Scan",
    nav_npk_calc: "NPK Calculator",
    nav_ananya_ai: "Ananya AI",
    nav_mandi: "Mandi & Weather",
    nav_farmer_stories: "Farmer Stories",
    nav_faq: "FAQ",
    nav_download_app: "Download App",
    nav_smart_farming: "Smart Farming Intelligence",
    google_sign_in: "Google Sign In",
    made_in_india: "Made in India",
    hero_pill: "GrainWise AI 🌾 · Next-Gen Precision Agriculture",
    hero_welcome: "Welcome to",
    hero_brand: "GrainWise AI! 🌾",
    hero_subtitle: "Smart farming starts with the right insights. Download the app today to get instant AI crop diagnostics, real-time Mandi updates, and 24/7 guidance from Ananya AI in your native language — all designed to help your fields thrive.",
    hero_cta_download: "Tap Download & Take Guesswork Out",
    hero_cta_google: "Sign in with Google",
    hero_cta_scan: "AI Scan",
    hero_metric_langs: "22 Languages",
    hero_metric_accuracy: "98.4% Diagnosis Accuracy",
    hero_metric_support: "24/7 Ananya AI Support",
    hero_preview_title: "Live AI Diagnostics Preview",
    hero_preview_cam: "Camera AI",
    hero_preview_cam_sub: "Instant leaf scan diagnosis",
    hero_preview_ananya_sub: "22 Native Languages",
    core_pillar_badge: "Three Core Pillars of GrainWise AI",
    core_title: "Designed to Help Your Fields",
    core_thrive: "Thrive",
    core_subtitle: "From instant field diagnostic scans to multi-lingual AI consultation and market intelligence, GrainWise AI puts expert agricultural technology directly in your hands.",
    core_explore: "Explore Interactive Feature",
    indigenous_badge: "100% Indigenous AI",
    atmanirbhar_title: "Proudly Made in India for Indian Farmers",
    atmanirbhar_desc: "Engineered specifically for Indian soil profiles, 22 regional Indian languages, and local Mandi ecosystem updates.",
    empower_title: "Empowering Every Farmer Across India",
    empower_sub: "Cutting-edge technology crafted for every crop, soil condition, and seasonal harvest.",
    diag_title: "Camera-Based AI Crop Diagnostics",
    diag_sub: "Point your phone camera at diseased crops to get instant AI diagnosis and targeted treatment remedies.",
    diag_upload_btn: "Upload Crop Photo",
    diag_scan_btn: "Start AI Scan",
    diag_analyzing: "Analyzing crop health with GrainWise AI...",
    diag_result_title: "Diagnosis & Remedies",
    npk_title: "Precision Soil NPK Fertilizer Calculator",
    npk_sub: "Calculate exact Nitrogen, Phosphorus, and Potassium requirements tailored to your crop, soil type, and farm size.",
    npk_calc_btn: "Calculate Optimal Dose",
    ananya_title: "Ananya AI Assistant",
    ananya_sub: "Ask any farming question in 22 native Indian languages.",
    ananya_placeholder: "Type your farming question in any language...",
    ananya_send: "Ask Ananya",
    mandi_title: "Real-Time Mandi Prices & MSP Locator",
    mandi_sub: "Live wholesale crop prices from over 2,500+ government regulated mandis across India.",
    mandi_search_crop: "Search crop (e.g. Wheat, Rice, Cotton)",
    mandi_search_state: "Filter by State",
    calendar_title: "Interactive Crop Calendar & PM Schemes",
    calendar_sub: "Seasonal planting advisories and Government subsidy information.",
    stories_title: "Real Impact on Indian Farms",
    stories_sub: "Hear from farmers who boosted their yield and reduced fertilizer costs using GrainWise AI.",
    faq_title: "Frequently Asked Questions",
    footer_hero_title: "From a single seed to a",
    footer_hero_gold: "bountiful harvest",
    footer_hero_sub: "Join thousands of farmers using GrainWise AI for real-time market prices, instant crop health checks, and a connected farming community.",
    footer_certified: "Certified AgriTech Platform · ISO 27001 Secured",
    footer_rights: "All rights reserved. Built for farmers with",
    modal_title: "Download GrainWise AI",
    modal_pre_register: "Android Pre-Register (Free 14 Days Trial Pack)",
    modal_scan_qr: "Scan Ultra-HD QR Code",
    modal_feedback_tab: "Update Phone Feedback"
  },

  Hindi: {
    nav_features: "विशेषताएं",
    nav_ai_scan: "एआई स्कैन",
    nav_npk_calc: "एनपीके कैलकुलेटर",
    nav_ananya_ai: "अनन्या एआई",
    nav_mandi: "मंडी और मौसम",
    nav_farmer_stories: "किसान कहानियां",
    nav_faq: "अक्सर पूछे जाने वाले प्रश्न",
    nav_download_app: "ऐप डाउनलोड करें",
    nav_smart_farming: "स्मार्ट कृषि इंटेलिजेंस",
    google_sign_in: "गूगल से साइन इन करें",
    made_in_india: "मेड इन इंडिया",
    hero_pill: "ग्रेनवाइज़ एआई 🌾 · अगली पीढ़ी की सटीक खेती",
    hero_welcome: "आपका स्वागत है",
    hero_brand: "ग्रेनवाइज़ एआई में! 🌾",
    hero_subtitle: "स्मार्ट खेती सही जानकारी से शुरू होती है। अपनी फसल के रोगों का तुरंत पता लगाने, लाइव मंडी भाव पाने और अपनी भाषा में 24/7 अनन्या एआई मार्गदर्शन पाने के लिए आज ही ऐप डाउनलोड करें।",
    hero_cta_download: "डाउनलोड करें और बेहतर उपज पाएं",
    hero_cta_google: "गूगल से साइन इन करें",
    hero_cta_scan: "एआई फसल जांच",
    hero_metric_langs: "22 भारतीय भाषाएं",
    hero_metric_accuracy: "98.4% सटीक जांच",
    hero_metric_support: "24/7 अनन्या एआई सहायता",
    hero_preview_title: "लाइव एआई डायग्नोस्टिक्स पूर्वावलोकन",
    hero_preview_cam: "कैमरा एआई",
    hero_preview_cam_sub: "पत्ती स्कैन से तुरंत जांच",
    hero_preview_ananya_sub: "22 क्षेत्रीय भाषाएं",
    core_pillar_badge: "ग्रेनवाइज़ एआई के तीन मुख्य स्तंभ",
    core_title: "आपके खेतों को समृद्ध बनाने के लिए",
    core_thrive: "विशेष निर्मित",
    core_subtitle: "त्वरित फसल निदान स्कैन से लेकर बहुभाषी एआई परामर्श और बाजार गुप्त जानकारी तक, ग्रेनवाइज़ एआई विशेषज्ञ कृषि तकनीक आपके हाथों में देता है।",
    core_explore: "इंटरैक्टिव सुविधा देखें",
    indigenous_badge: "100% स्वदेशी एआई",
    atmanirbhar_title: "भारतीय किसानों के लिए गर्व से मेड इन इंडिया",
    atmanirbhar_desc: "विशेष रूप से भारतीय मिट्टी के प्रकारों, 22 क्षेत्रीय भाषाओं और स्थानीय मंडी प्रणाली के लिए निर्मित।",
    empower_title: "भारत भर के हर किसान को सशक्त बनाना",
    empower_sub: "हर फसल, मिट्टी की स्थिति और मौसमी फसल के लिए बनाई गई अत्याधुनिक तकनीक।",
    diag_title: "कैमरा-आधारित एआई फसल निदान",
    diag_sub: "रोगग्रस्त पत्तियों पर फोन कैमरा घुमाएं और तुरंत एआई निदान और सटीक उपचार पाएं।",
    diag_upload_btn: "फसल फोटो अपलोड करें",
    diag_scan_btn: "एआई स्कैन शुरू करें",
    diag_analyzing: "ग्रेनवाइज़ एआई फसल स्वास्थ्य की जांच कर रहा है...",
    diag_result_title: "निदान और उपचार परामर्श",
    npk_title: "सटीक मिट्टी एनपीके उर्वरक कैलकुलेटर",
    npk_sub: "अपनी फसल, मिट्टी के प्रकार और खेत के आकार के अनुसार सटीक नाइट्रोजन, फास्फोरस और पोटाश की गणना करें।",
    npk_calc_btn: "सटीक खुराक की गणना करें",
    ananya_title: "अनन्या एआई सहायक",
    ananya_sub: "22 भारतीय भाषाओं में खेती से जुड़ा कोई भी सवाल पूछें।",
    ananya_placeholder: "अपनी भाषा में कृषि संबंधी सवाल लिखें...",
    ananya_send: "अनन्या से पूछें",
    mandi_title: "लाइव मंडी भाव और एमएसपी",
    mandi_sub: "भारत की 2,500+ सरकारी मंडियों से फसलों के ताजा थोक भाव और न्यूनतम समर्थन मूल्य।",
    mandi_search_crop: "फसल खोजें (जैसे गेहूं, धान, कपास)",
    mandi_search_state: "राज्य के अनुसार फ़िल्टर करें",
    calendar_title: "इंटरैक्टिव फसल कैलेंडर और सरकारी योजनाएं",
    calendar_sub: "मौसमी बुवाई सलाह और पीएम किसान सब्सिडी की पूरी जानकारी।",
    stories_title: "भारतीय खेतों पर वास्तविक प्रभाव",
    stories_sub: "उन किसानों से सुनें जिन्होंने ग्रेनवाइज़ एआई का उपयोग करके अपनी उपज बढ़ाई और खाद की लागत कम की।",
    faq_title: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
    footer_hero_title: "एक छोटे से बीज से लेकर",
    footer_hero_gold: "बंपर फसल तक",
    footer_hero_sub: "हजारों किसानों के साथ जुड़ें जो ताजा मंडी भाव, त्वरित फसल स्वास्थ्य जांच और समुदाय के लिए ग्रेनवाइज़ एआई का उपयोग कर रहे हैं।",
    footer_certified: "प्रमाणित एग्रीटेक प्लेटफॉर्म · ISO 27001 सुरक्षित",
    footer_rights: "सर्वाधिकार सुरक्षित। किसानों के लिए समर्पित भाव से निर्मित",
    modal_title: "ग्रेनवाइज़ एआई डाउनलोड करें",
    modal_pre_register: "एंड्रॉइड प्री-रजिस्टर (मुफ्त 14 दिनों का ट्रायल पैक)",
    modal_scan_qr: "अल्ट्रा-एचडी क्यूआर कोड स्कैन करें",
    modal_feedback_tab: "फ़ोन फीडबैक अपडेट करें"
  },

  Tamil: {
    nav_features: "அம்சங்கள்",
    nav_ai_scan: "AI ஸ்கேன்",
    nav_npk_calc: "NPK கணிப்பான்",
    nav_ananya_ai: "அனன்யா AI",
    nav_mandi: "சந்தை & வானிலை",
    nav_farmer_stories: "விவசாயி கதைகள்",
    nav_faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    nav_download_app: "செயலியைப் பதிவிறக்கவும்",
    nav_smart_farming: "ஸ்மார்ட் விவசாய நுன்னறிவு",
    google_sign_in: "கூகிள் மூலம் உள்நுழைக",
    made_in_india: "மேட் இன் இந்தியா",
    hero_pill: "GrainWise AI 🌾 · அடுத்த தலைமுறை துல்லிய விவசாயம்",
    hero_welcome: "வரவேற்கிறோம்",
    hero_brand: "GrainWise AI க்கு! 🌾",
    hero_subtitle: "ஸ்மார்ட் விவசாயம் சரியான தகவல்களுடன் தொடங்குகிறது. பயிர் நோய் கண்டறிதல், நேரலை சந்தை விலை மற்றும் உங்கள் தாய்மொழியில் 24/7 அனன்யா AI வழிகாட்டுதலைப் பெற இன்றே பதிவிறக்குங்கள்.",
    hero_cta_download: "பதிவிறக்கி விளைச்சலை உயர்த்தவும்",
    hero_cta_google: "கூகிள் உள்நுழைவு",
    hero_cta_scan: "AI பயிர் பரிசோதனை",
    hero_metric_langs: "22 இந்திய மொழிகள்",
    hero_metric_accuracy: "98.4% துல்லிய நோய் கண்டறிதல்",
    hero_metric_support: "24/7 அனன்யா AI உதவி",
    hero_preview_title: "நேரலை AI பரிசோதனை",
    hero_preview_cam: "கேமரா AI",
    hero_preview_cam_sub: "இலை ஸ்கேன் மூலம் உடனடி பரிசோதனை",
    hero_preview_ananya_sub: "22 தாய்மொழிகள்",
    core_pillar_badge: "GrainWise AI இன் 3 முக்கிய தூண்கள்",
    core_title: "உங்கள் நிலங்களைச் செழிக்க வைக்க",
    core_thrive: "வடிவமைக்கப்பட்டது",
    core_subtitle: "உடனடி பயிர் நோய் பரிசோதனை முதல் பன்மொழி AI ஆலோசனை வரை, GrainWise AI விவசாய தொழில்நுட்பத்தை உங்கள் கைகளில் வழங்குகிறது.",
    core_explore: "அம்சங்களை ஆராயுங்கள்",
    indigenous_badge: "100% இந்திய AI",
    atmanirbhar_title: "இந்திய விவசாயிகளுக்காக பெருமையுடன் மேட் இன் இந்தியா",
    atmanirbhar_desc: "இந்திய மண் மற்றும் 22 மொழிகளுக்காக சிறப்புடன் உருவாக்கப்பட்டது.",
    empower_title: "இந்திய விவசாயிகள் ஒவ்வொருவரையும் சக்திமயமாக்குதல்",
    empower_sub: "ஒவ்வொரு பயிர் மற்றும் பருவகால விளைச்சலுக்கான அதிநவீன தொழில்நுட்பம்.",
    diag_title: "கேமரா அடிப்படையிலான AI பயிர் பரிசோதனை",
    diag_sub: "பாதிக்கப்பட்ட இலையை மொபைல் கேமராவில் காட்டி உடனடி பரிசோதனையும் சிகிச்சையும் பெறுங்கள்.",
    diag_upload_btn: "புகைப்படம் பதிவேற்றவும்",
    diag_scan_btn: "AI ஸ்கேன் தொடங்கு",
    diag_analyzing: "பயிரின் ஆரோக்கியம் பரிசோதிக்கப்படுகிறது...",
    diag_result_title: "பரிசோதனை முடிவுகள் & தீர்வுகள்",
    npk_title: "துல்லிய NPK உர கணிப்பான்",
    npk_sub: "உங்கள் மண் மற்றும் பயிரின் அளவுக்கு ஏற்ப தேவையான உர அளவைக் கணக்கிடுங்கள்.",
    npk_calc_btn: "உர அளவைக் கணக்கிடு",
    ananya_title: "அனன்யா AI உதவியாளர்",
    ananya_sub: "22 மொழிகளில் உங்கள் விவசாயக் கேள்விகளைக் கேளுங்கள்.",
    ananya_placeholder: "கேள்வியை டைப் செய்யுங்கள்...",
    ananya_send: "கேட்கவும்",
    mandi_title: "நேரலை சந்தை விலைகள் & MSP",
    mandi_sub: "இந்தியாவில் உள்ள 2,500+ அரசு ஒழுங்குமுறை விற்பனைக்கூடங்களின் நேரலை விலைகள்.",
    mandi_search_crop: "பயிரைத் தேடவும்",
    mandi_search_state: "மாநில வாரியாகத் தேடவும்",
    calendar_title: "பயிர் காலண்டர் & அரசு திட்டங்கள்",
    calendar_sub: "பருவகால சாகுபடி ஆலோசனைகள் மற்றும் மானிய தகவல்கள்.",
    stories_title: "இந்திய விவசாய நிலங்களில் உண்மையான தாக்கம்",
    stories_sub: "GrainWise AI மூலம் விளைச்சலை அதிகரித்து உரச் செலவைக் குறைத்த விவசாயிகளின் அனுபவங்கள்.",
    faq_title: "கேள்விகள் மற்றும் பதில்கள்",
    footer_hero_title: "ஒரு சிறிய விதையிலிருந்து",
    footer_hero_gold: "அற்புதமான அறுவடை வரை",
    footer_hero_sub: "சந்தை விலை மற்றும் பயிர் பரிசோதனைக்கு GrainWise AI ஐப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் இணையுங்கள்.",
    footer_certified: "சான்றளிக்கப்பட்ட அக்ரிடெக் தளம் · ISO 27001 பாதுகாப்பு",
    footer_rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. விவசாயிகளுக்காக அன்புடன் உருவாக்கப்பட்டது",
    modal_title: "GrainWise AI பதிவிறக்கவும்",
    modal_pre_register: "ஆண்ட்ராய்டு முன்பதிவு (இலவச 14 நாட்கள் சோதனைக் கட்டணம்)",
    modal_scan_qr: "QR குறியீட்டை ஸ்கேன் செய்யுங்கள்",
    modal_feedback_tab: "கருத்துக்களைப் புதுப்பிக்கவும்"
  },

  Telugu: {
    nav_features: "ఫీచర్లు",
    nav_ai_scan: "AI స్కాన్",
    nav_npk_calc: "NPK క్యాలిక్యులేటర్",
    nav_ananya_ai: "అనన్య AI",
    nav_mandi: "మార్కెట్ & వాతావరణం",
    nav_farmer_stories: "రైతుల కథనాలు",
    nav_faq: "తరచుగా అడిగే ప్రశ్నలు",
    nav_download_app: "యాప్ డౌన్‌లోడ్ చేయండి",
    nav_smart_farming: "స్మార్ట్ అగ్రికల్చర్ ఇంటెలిజెన్స్",
    google_sign_in: "గూగుల్‌తో సైన్ ఇన్ చేయండి",
    made_in_india: "మేడ్ ఇన్ ఇండియా",
    hero_pill: "గ్రెయిన్ వైజ్ AI 🌾 · తదుపరి తరం ఖచ్చితమైన వ్యవసాయం",
    hero_welcome: "స్వాగతం",
    hero_brand: "గ్రెయిన్ వైజ్ AI కి! 🌾",
    hero_subtitle: "స్మార్ట్ వ్యవసాయం సరైన సమాచారంతో ప్రారంభమవుతుంది. పంట తెగుళ్ల నిర్ధారణ, లైవ్ మార్కెట్ ధరలు మరియు మీ మాతృభాషలో 24/7 అనన్య AI మార్గదర్శకత్వం కోసం ఈరోజే యాప్‌ను డౌన్‌లోడ్ చేసుకోండి.",
    hero_cta_download: "డౌన్‌లోడ్ చేసి దిగుబడి పెంచుకోండి",
    hero_cta_google: "గూగుల్ సైన్ ఇన్",
    hero_cta_scan: "AI పంట స్కాన్",
    hero_metric_langs: "22 భారతీయ భాషలు",
    hero_metric_accuracy: "98.4% ఖచ్చితమైన నిర్ధారణ",
    hero_metric_support: "24/7 అనన్య AI సహాయం",
    hero_preview_title: "లైవ్ AI నిర్ధారణ పరిదృశ్యం",
    hero_preview_cam: "కెమెరా AI",
    hero_preview_cam_sub: "ఆకు స్కాన్‌తో తక్షణ నిర్ధారణ",
    hero_preview_ananya_sub: "22 ప్రాంతీయ భాషలు",
    core_pillar_badge: "గ్రెయిన్ వైజ్ AI యొక్క 3 ముఖ్యమైన స్తంభాలు",
    core_title: "మీ పొలాలను సమృద్ధిగా చేయడానికి",
    core_thrive: "రూపొందించబడింది",
    core_subtitle: "తక్షణ పంట వ్యాధి స్కాన్‌ల నుండి బహుభాషా AI సలహాల వరకు, గ్రెయిన్ వైజ్ AI అధునాతన వ్యవసాయ సాంకేతికతను మీ చేతుల్లో ఉంచుతుంది.",
    core_explore: "ఫీచర్లను అన్వేషించండి",
    indigenous_badge: "100% స్వదేశీ AI",
    atmanirbhar_title: "భారతీయ రైతుల కోసం గర్వంగా మేడ్ ఇన్ ఇండియా",
    atmanirbhar_desc: "ప్రత్యేకంగా భారతీయ నేలలు మరియు 22 భాషల కోసం తయారు చేయబడింది.",
    empower_title: "భారతదేశంలోని ప్రతి రైతును సాధికారపరచడం",
    empower_sub: "ప్రతి పంట మరియు సీజన్ కోసం రూపొందించిన సాంకేతికత.",
    diag_title: "కెమెరా ఆధారిత AI పంట నిర్ధారణ",
    diag_sub: "వ్యాధి ఉన్న ఆకులపై ఫోన్ కెమెరాను ఉంచి తక్షణ AI నిర్ధారణ మరియు చికిత్స పొందండి.",
    diag_upload_btn: "ఫోటో అప్‌లోడ్ చేయండి",
    diag_scan_btn: "AI స్కాన్ ప్రారంభించండి",
    diag_analyzing: "పంట ఆరోగ్యాన్ని విశ్లేషిస్తోంది...",
    diag_result_title: "నిర్ధారణ & నివారణ మార్గాలు",
    npk_title: "సరియైన NPK ఎరువుల క్యాలిక్యులేటర్",
    npk_sub: "మీ పొలం పరిమాణం మరియు నేల రకానికి తగిన ఎరువుల మోతాదును లెక్కించండి.",
    npk_calc_btn: "ఎరువుల మోతాదును లెక్కించండి",
    ananya_title: "అనన్య AI అసిస్టెంట్",
    ananya_sub: "22 భాషల్లో మీ వ్యవసాయ సందేహాలను అడగండి.",
    ananya_placeholder: "మీ భాషలో ప్రశ్న టైప్ చేయండి...",
    ananya_send: "అడగండి",
    mandi_title: "లైవ్ మార్కెట్ ధరలు & MSP",
    mandi_sub: "భారతదేశంలోని 2,500+ ప్రభుత్వ మార్కెట్‌ల నుండి తాజా ధరలు.",
    mandi_search_crop: "పంటను వెతకండి",
    mandi_search_state: "రాష్ట్రం వారీగా శోధించండి",
    calendar_title: "పంట క్యాలెండర్ & ప్రభుత్వ పథకాలు",
    calendar_sub: "సీజనల్ వ్యవసాయ సూచనలు మరియు సబ్సిడీ వివరాలు.",
    stories_title: "రైతుల పొలాల్లో నిజమైన మార్పు",
    stories_sub: "గ్రెయిన్ వైజ్ AI ద్వారా దిగుబడి పెంచుకున్న రైతుల అనుభవాలు.",
    faq_title: "తరచుగా అడిగే ప్రశ్నలు",
    footer_hero_title: "ఒక చిన్న విత్తనం నుండి",
    footer_hero_gold: "సమృద్ధిగా పంట వరకు",
    footer_hero_sub: "తాజా మార్కెట్ ధరలు మరియు పంట నిర్ధారణ కోసం గ్రెయిన్ వైజ్ AI ఉపయోగిస్తున్న వేలాది మంది రైతులతో కలవండి.",
    footer_certified: "ధృవీకరించబడిన అగ్రిటెక్ ప్లాట్‌ఫారమ్ · ISO 27001 రక్షణ",
    footer_rights: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. రైతుల కోసం ప్రేమతో తయారుచేయబడింది",
    modal_title: "గ్రెయిన్ వైజ్ AI డౌన్‌లోడ్ చేయండి",
    modal_pre_register: "ఆండ్రాయిడ్ ప్రి-రిజిస్టర్ (ఉచిత 14 రోజులు ట్రియల్ ప్యాక్)",
    modal_scan_qr: "QR కోడ్ స్కాన్ చేయండి",
    modal_feedback_tab: "ఫీడ్‌బ్యాక్ అప్‌డేట్ చేయండి"
  },

  Punjabi: {
    nav_features: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    nav_ai_scan: "AI ਸਕੈਨ",
    nav_npk_calc: "NPK ਕੈਲਕੁਲੇਟਰ",
    nav_ananya_ai: "ਅਨਨਿਆ AI",
    nav_mandi: "ਮੰਡੀ ਅਤੇ ਮੌਸਮ",
    nav_farmer_stories: "ਕਿਸਾਨਾਂ ਦੀਆਂ ਕਹਾਣੀਆਂ",
    nav_faq: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    nav_download_app: "ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ",
    nav_smart_farming: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਇੰਟੈਲੀਜੈਂਸ",
    google_sign_in: "ਗੂਗਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ",
    made_in_india: "ਮੇਡ ਇਨ ਇੰਡੀਆ",
    hero_pill: "ਗ੍ਰੇਨਵਾਈਜ਼ AI 🌾 · ਅਗਲੀ ਪੀੜ੍ਹੀ ਦੀ ਸਟੀਕ ਖੇਤੀ",
    hero_welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    hero_brand: "ਗ੍ਰੇਨਵਾਈਜ਼ AI ਵਿੱਚ! 🌾",
    hero_subtitle: "ਸਮਾਰਟ ਖੇਤੀ ਸਹੀ ਜਾਣਕਾਰੀ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ। ਫਸਲਾਂ ਦੀਆਂ ਬੀਮਾਰੀਆਂ ਦੀ ਤੁਰੰਤ ਜਾਂਚ, ਲਾਈਵ ਮੰਡੀ ਭਾਅ ਅਤੇ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ 24/7 ਅਨਨਿਆ AI ਮਾਰਗਦਰਸ਼ਨ ਲਈ ਅੱਜ ਹੀ ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ।",
    hero_cta_download: "ਡਾਊਨਲੋਡ ਕਰੋ ਅਤੇ ਵਧੀਆ ਝਾੜ ਲਓ",
    hero_cta_google: "ਗੂਗਲ ਸਾਈਨ ਇਨ",
    hero_cta_scan: "AI ਫਸਲ ਜਾਂਚ",
    hero_metric_langs: "22 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ",
    hero_metric_accuracy: "98.4% ਸਟੀਕ ਜਾਂਚ",
    hero_metric_support: "24/7 ਅਨਨਿਆ AI ਸਹਾਇਤਾ",
    hero_preview_title: "ਲਾਈਵ AI ਡਾਇਗਨੌਸਟਿਕਸ",
    hero_preview_cam: "ਕੈਮਰਾ AI",
    hero_preview_cam_sub: "ਪੱਤੇ ਦੇ ਸਕੈਨ ਤੋਂ ਤੁਰੰਤ ਜਾਂਚ",
    hero_preview_ananya_sub: "22 ਖੇਤਰੀ ਭਾਸ਼ਾਵਾਂ",
    core_pillar_badge: "ਗ੍ਰੇਨਵਾਈਜ਼ AI ਦੇ ਤਿੰਨ ਮੁੱਖ ਥੰਮ੍ਹ",
    core_title: "ਤੁਹਾਡੇ ਖੇਤਾਂ ਨੂੰ ਖੁਸ਼ਹਾਲ ਬਣਾਉਣ ਲਈ",
    core_thrive: "ਤਿਆਰ ਕੀਤਾ ਗਿਆ",
    core_subtitle: "ਤੁਰੰਤ ਫਸਲ ਬੀਮਾਰੀ ਜਾਂਚ ਤੋਂ ਲੈ ਕੇ ਬਹੁ-ਭਾਸ਼ਾਈ AI ਸਲਾਹ ਤੱਕ, ਗ੍ਰੇਨਵਾਈਜ਼ AI ਖੇਤੀ ਤਕਨਾਲੋਜੀ ਤੁਹਾਡੇ ਹੱਥਾਂ ਵਿੱਚ ਦਿੰਦਾ ਹੈ।",
    core_explore: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਵੇਖੋ",
    indigenous_badge: "100% ਸਵਦੇਸ਼ੀ AI",
    atmanirbhar_title: "ਭਾਰਤੀ ਕਿਸਾਨਾਂ ਲਈ ਮਾਣ ਨਾਲ ਮੇਡ ਇਨ ਇੰਡੀਆ",
    atmanirbhar_desc: "ਖਾਸ ਤੌਰ 'ਤੇ ਭਾਰਤੀ ਮਿੱਟੀ ਅਤੇ 22 ਭਾਸ਼ਾਵਾਂ ਲਈ ਬਣਾਇਆ ਗਿਆ।",
    empower_title: "ਭਾਰਤ ਦੇ ਹਰ ਕਿਸਾਨ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣਾ",
    empower_sub: "ਹਰ ਫਸਲ ਅਤੇ ਮੌਸਮ ਲਈ ਬਣਾਈ ਗਈ ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ।",
    diag_title: "ਕੈਮਰਾ-ਆਧਾਰਿਤ AI ਫਸਲ ਜਾਂਚ",
    diag_sub: "ਬੀਮਾਰ ਪੱਤੇ 'ਤੇ ਫੋਨ ਕੈਮਰਾ ਘੁਮਾਓ ਅਤੇ ਤੁਰੰਤ AI ਜਾਂਚ ਅਤੇ ਇਲਾਜ ਪਾਓ।",
    diag_upload_btn: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    diag_scan_btn: "AI ਸਕੈਨ ਸ਼ੁਰੂ ਕਰੋ",
    diag_analyzing: "ਫਸਲ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    diag_result_title: "ਜਾਂਚ ਅਤੇ ਇਲਾਜ",
    npk_title: "ਸਟੀਕ NPK ਖਾਦ ਕੈਲਕੁਲੇਟਰ",
    npk_sub: "ਆਪਣੀ ਫਸਲ ਅਤੇ ਖੇਤ ਦੇ ਆਕਾਰ ਅਨੁਸਾਰ ਸਹੀ ਖਾਦ ਦੀ ਮਾਤਰਾ ਦੀ ਗਣਨਾ ਕਰੋ।",
    npk_calc_btn: "ਖਾਦ ਦੀ ਗਣਨਾ ਕਰੋ",
    ananya_title: "ਅਨਨਿਆ AI ਸਹਾਇਕ",
    ananya_sub: "22 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਖੇਤੀ ਨਾਲ ਜੁੜਿਆ ਕੋਈ ਵੀ ਸਵਾਲ ਪੁੱਛੋ।",
    ananya_placeholder: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਵਾਲ ਲਿਖੋ...",
    ananya_send: "ਪੁੱਛੋ",
    mandi_title: "ਲਾਈਵ ਮੰਡੀ ਭਾਅ ਅਤੇ MSP",
    mandi_sub: "ਭਾਰਤ ਦੀਆਂ 2,500+ ਮੰਡੀਆਂ ਦੇ ਤਾਜ਼ਾ ਸਰਕਾਰੀ ਭਾਅ।",
    mandi_search_crop: "ਫਸਲ ਖੋਜੋ (ਜਿਵੇਂ ਕਣਕ, ਝੋਨਾ)",
    mandi_search_state: "ਰਾਜ ਅਨੁਸਾਰ ਫਿਲਟਰ ਕਰੋ",
    calendar_title: "ਫਸਲ ਕੈਲੰਡਰ ਅਤੇ ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    calendar_sub: "ਮੌਸਮੀ ਬੀਜਾਈ ਸਲਾਹ ਅਤੇ ਸਰਕਾਰੀ ਸਬਸਿਡੀਆਂ ਦੀ ਜਾਣਕਾਰੀ।",
    stories_title: "ਖੇਤਾਂ ਵਿੱਚ ਅਸਲ ਸੁਧਾਰ",
    stories_sub: "ਉਨ੍ਹਾਂ ਕਿਸਾਨਾਂ ਤੋਂ ਸੁਣੋ ਜਿਨ੍ਹਾਂ ਨੇ ਗ੍ਰੇਨਵਾਈਜ਼ AI ਨਾਲ ਝਾੜ ਵਧਾਇਆ।",
    faq_title: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    footer_hero_title: "ਇੱਕ ਛੋਟੇ ਬੀਜ ਤੋਂ ਲੈ ਕੇ",
    footer_hero_gold: "ਸ਼ਾਨਦਾਰ ਫਸਲ ਤੱਕ",
    footer_hero_sub: "ਤਾਜ਼ਾ ਮੰਡੀ ਭਾਅ ਅਤੇ ਫਸਲ ਜਾਂਚ ਲਈ ਗ੍ਰੇਨਵਾਈਜ਼ AI ਵਰਤਣ ਵਾਲੇ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ।",
    footer_certified: "ਸਰਟੀਫਾਈਡ ਐਗਰੀਟੈਕ ਪਲੇਟਫਾਰਮ · ISO 27001 ਸੁਰੱਖਿਅਤ",
    footer_rights: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ। ਕਿਸਾਨਾਂ ਲਈ ਪਿਆਰ ਨਾਲ ਬਣਾਇਆ ਗਿਆ",
    modal_title: "ਗ੍ਰੇਨਵਾਈਜ਼ AI ਡਾਊਨਲੋਡ ਕਰੋ",
    modal_pre_register: "ਐਂਡਰੌਇਡ ਪ੍ਰੀ-ਰਜਿਸਟਰ (ਮੁਫ਼ਤ 14 ਦਿਨਾਂ ਦਾ ਟਰਾਇਲ)",
    modal_scan_qr: "QR ਕੋਡ ਸਕੈਨ ਕਰੋ",
    modal_feedback_tab: "ਫੀਡਬੈਕ ਅਪਡੇਟ ਕਰੋ"
  },

  Bengali: {
    nav_features: "বৈশিষ্ট্যসমূহ",
    nav_ai_scan: "এআই স্ক্যান",
    nav_npk_calc: "এনপিকে ক্যালকুলেটর",
    nav_ananya_ai: "অনন্যা এআই",
    nav_mandi: "মন্ডি ও আবহাওয়া",
    nav_farmer_stories: "কৃষকদের গল্প",
    nav_faq: "প্রশ্নোত্তর",
    nav_download_app: "অ্যাপ ডাউনলোড করুন",
    nav_smart_farming: "স্মার্ট কৃষি বুদ্ধিমত্তা",
    google_sign_in: "গুগল সাইন ইন",
    made_in_india: "মেড ইন ইন্ডিয়া",
    hero_pill: "গ্রেনওয়াইজ এআই 🌾 · আধুনিক নিখুঁত কৃষি প্রযুক্তি",
    hero_welcome: "স্বাগতম",
    hero_brand: "গ্রেনওয়াইজ এআই-তে! 🌾",
    hero_subtitle: "স্মার্ট চাষাবাদ সঠিক তথ্যের মাধ্যমে শুরু হয়। ফসলের রোগের তাৎক্ষণিক নির্ণয়, লাইভ মান্ডির দর এবং আপনার নিজের ভাষায় ২৪/৭ অনন্যা এআই নির্দেশিকা পেতে আজই অ্যাপটি ডাউনলোড করুন।",
    hero_cta_download: "ডাউনলোড করুন এবং ভালো ফলন পান",
    hero_cta_google: "গুগল দিয়ে সাইন ইন করুন",
    hero_cta_scan: "এআই ফসল স্ক্যান",
    hero_metric_langs: "২২টি ভারতীয় ভাষা",
    hero_metric_accuracy: "৯৮.৪% নির্ভুল রোগ নির্ণয়",
    hero_metric_support: "২৪/৭ অনন্যা এআই সহায়তা",
    hero_preview_title: "লাইভ এআই রোগ নির্ণয় প্রিভিউ",
    hero_preview_cam: "ক্যামেরা এআই",
    hero_preview_cam_sub: "পাতা স্ক্যান করে তাৎক্ষণিক রোগ নির্ণয়",
    hero_preview_ananya_sub: "২২টি আঞ্চলিক ভাষা",
    core_pillar_badge: "গ্রেনওয়াইজ এআই-এর তিনটি মূল স্তম্ভ",
    core_title: "আপনার জমিকে সমৃদ্ধ করতে",
    core_thrive: "বিশেষভাবে তৈরি",
    core_subtitle: "তাৎক্ষণিক ফসলের রোগ নির্ণয় থেকে শুরু করে বহুভাষিক এআই পরামর্শ, গ্রেনওয়াইজ এআই উন্নত কৃষি প্রযুক্তি আপনার হাতের মুঠোয় এনে দেয়।",
    core_explore: "বৈশিষ্ট্যগুলো জানুন",
    indigenous_badge: "১০০% স্বদেশী এআই",
    atmanirbhar_title: "ভারতীয় কৃষকদের জন্য সগর্বে মেড ইন ইন্ডিয়া",
    atmanirbhar_desc: "বিশেষভাবে ভারতীয় মাটি, ২২টি ভাষা এবং স্থানীয় মান্ডি ব্যবস্থার জন্য তৈরি।",
    empower_title: "ভারতের প্রতিটি কৃষককে ক্ষমতায়িত করা",
    empower_sub: "প্রতিটি ফসল ও মরশুমের জন্য তৈরি আধুনিক প্রযুক্তি।",
    diag_title: "ক্যামেরা ভিত্তিক এআই ফসল রোগ নির্ণয়",
    diag_sub: "আক্রান্ত পাতার দিকে ফোন ক্যামেরা ধরুন এবং তাৎক্ষণিক এআই রোগ নির্ণয় ও প্রতিকার পান।",
    diag_upload_btn: "ছবি আপলোড করুন",
    diag_scan_btn: "এআই স্ক্যান শুরু করুন",
    diag_analyzing: "ফসলের স্বাস্থ্য পরীক্ষা করা হচ্ছে...",
    diag_result_title: "রোগ নির্ণয় ও সমাধান",
    npk_title: "সঠিক এনপিকে সার ক্যালকুলেটর",
    npk_sub: "আপনার ফসল, মাটির ধরন এবং জমির পরিমাণ অনুযায়ী সারের সঠিক মাত্রা গণনা করুন।",
    npk_calc_btn: "সারের সঠিক মাত্রা হিসাব করুন",
    ananya_title: "অনন্যা এআই সহকারী",
    ananya_sub: "২২টি ভারতীয় ভাষায় কৃষিসংক্রান্ত যেকোনো প্রশ্ন জিজ্ঞাসা করুন।",
    ananya_placeholder: "আপনার নিজের ভাষায় প্রশ্ন লিখুন...",
    ananya_send: "জিজ্ঞাসা করুন",
    mandi_title: "লাইভ মান্ডির দর ও এমএসপি",
    mandi_sub: "ভারতের ২৫০০+ সরকারি মান্ডি থেকে ফসলের তাজা পাইকারি দর।",
    mandi_search_crop: "ফসল খুঁজুন (যেমন ধান, গম, পাট)",
    mandi_search_state: "রাজ্য অনুযায়ী খুঁজুন",
    calendar_title: "ফসল ক্যালেন্ডার ও সরকারি প্রকল্প",
    calendar_sub: "মরশুমি চাষের পরামর্শ এবং পিএম কিষাণ ভর্তুকির তথ্য।",
    stories_title: "ভারতীয় কৃষকদের বাস্তব জীবনের সাফল্য",
    stories_sub: "যে কৃষকরা গ্রেনওয়াইজ এআই ব্যবহার করে ফলন বাড়িয়েছেন তাদের কথা শুনুন।",
    faq_title: "সাধারণ জিজ্ঞাস্য (FAQ)",
    footer_hero_title: "একটি ছোট বীজ থেকে শুরু করে",
    footer_hero_gold: "প্রচুর ফলন পর্যন্ত",
    footer_hero_sub: "তাজা মান্ডির দর ও ফসলের স্বাস্থ্য পরীক্ষার জন্য গ্রেনওয়াইজ এআই ব্যবহারকারী হাজার হাজার কৃষকের সাথে যুক্ত হন।",
    footer_certified: "স্বীকৃত অ্যাগ্রিটেক প্ল্যাটফর্ম · ISO 27001 সুরক্ষিত",
    footer_rights: "সর্বস্বত্ব সংরক্ষিত। কৃষকদের প্রতি ভালোবাসায় তৈরি",
    modal_title: "গ্রেনওয়াইজ এআই ডাউনলোড করুন",
    modal_pre_register: "অ্যান্ড্রয়েড প্রাক-নিবন্ধন (বিনামূল্যে ১৪ দিনের ট্রায়াল প্যাক)",
    modal_scan_qr: "QR কোড স্ক্যান করুন",
    modal_feedback_tab: "মতামত আপডেট করুন"
  },

  Marathi: {
    nav_features: "वैशिष्ट्ये",
    nav_ai_scan: "एआय स्कॅन",
    nav_npk_calc: "एनपीके कॅल्क्युलेटर",
    nav_ananya_ai: "अनन्या एआय",
    nav_mandi: "बाजारभाव व हवामान",
    nav_farmer_stories: "शेतकऱ्यांच्या गोष्टी",
    nav_faq: "वारंवार विचारले जाणारे प्रश्न",
    nav_download_app: "ॲप डाउनलोड करा",
    nav_smart_farming: "स्मार्ट कृषी बुद्धिमत्ता",
    google_sign_in: "गुगलने साइन इन करा",
    made_in_india: "मेड इन इंडिया",
    hero_pill: "ग्रेनवाईज एआय 🌾 · पुढील पिढीची अचूक शेती",
    hero_welcome: "स्वागत आहे",
    hero_brand: "ग्रेनवाईज एआय मध्ये! 🌾",
    hero_subtitle: "स्मार्ट शेती योग्य माहितीने सुरू होते. पिकांवरील रोगांचे त्वरित निदान, लाईव्ह बाजारभाव आणि तुमच्या भाषेत २४/७ अनन्या एआय मार्गदर्शन मिळवण्यासाठी आजच ॲप डाउनलोड करा.",
    hero_cta_download: "डाउनलोड करा आणि उत्पन्न वाढवा",
    hero_cta_google: "गुगल साइन इन",
    hero_cta_scan: "एआय पीक तपासणी",
    hero_metric_langs: "२२ भारतीय भाषा",
    hero_metric_accuracy: "९८.४% अचूक निदान",
    hero_metric_support: "२४/७ अनन्या एआय मदत",
    hero_preview_title: "लाईव्ह एआय निदान पूर्वदृश्य",
    hero_preview_cam: "कॅमेरा एआय",
    hero_preview_cam_sub: "पानाच्या स्कॅनवरून त्वरित रोग निदान",
    hero_preview_ananya_sub: "२२ प्रादेशिक भाषा",
    core_pillar_badge: "ग्रेनवाईज एआय चे ३ मुख्य स्तंभ",
    core_title: "तुमची शेती समृद्ध करण्यासाठी",
    core_thrive: "विशेष निर्मित",
    core_subtitle: "त्वरित पीक रोग निदानापासून ते बहुभाषिक एआय सल्ल्यापर्यंत, ग्रेनवाईज एआय प्रगत तंत्रज्ञान तुमच्या हातात देते.",
    core_explore: "वैशिष्ट्ये पहा",
    indigenous_badge: "१००% स्वदेशी एआय",
    atmanirbhar_title: "भारतीय शेतकऱ्यांसाठी अभिमानाने मेड इन इंडिया",
    atmanirbhar_desc: "खास भारतीय माती, २२ भाषा आणि स्थानिक बाजारपेठेसाठी विकसित.",
    empower_title: "भारतातील प्रत्येक शेतकऱ्याला सक्षम करणे",
    empower_sub: "प्रत्येक पीक आणि हंगामासाठी तयार केलेले आधुनिक तंत्रज्ञान.",
    diag_title: "कॅमेरा आधारित एआय पीक रोग निदान",
    diag_sub: "किडलेल्या पानांवर मोबाईल कॅमेरा धरा आणि त्वरित एआय निदान व उपाय मिळवा.",
    diag_upload_btn: "फोटो अपलोड करा",
    diag_scan_btn: "एआय स्कॅन सुरू करा",
    diag_analyzing: "पिकाच्या आरोग्याची तपासणी होत आहे...",
    diag_result_title: "निदान आणि उपाय",
    npk_title: "अचूक माती एनपीके खत कॅल्क्युलेटर",
    npk_sub: "तुमचे पीक, मातीचा प्रकार आणि क्षेत्रफळानुसार खतांची अचूक मात्रा मोजा.",
    npk_calc_btn: "खतांची मात्रा मोजा",
    ananya_title: "अनन्या एआय सहाय्यक",
    ananya_sub: "२२ भाषांमध्ये शेतीविषयक कोणताही प्रश्न विचारा.",
    ananya_placeholder: "तुमच्या भाषेत प्रश्न लिहा...",
    ananya_send: "विचारा",
    mandi_title: "लाईव्ह बाजारभाव आणि एमएसपी",
    mandi_sub: "भारतातील २५००+ बाजार समित्यांमधील शेतमालाचे ताजे दर.",
    mandi_search_crop: "पीक शोधा (उदा. कापूस, सोयाबीन, गहू)",
    mandi_search_state: "राज्यानुसार फिल्टर करा",
    calendar_title: "पीक कॅलेंडर आणि शासकीय योजना",
    calendar_sub: "हंगामांनुसार लागवड सल्ला आणि शासकीय अनुदानाची माहिती.",
    stories_title: "भारतीय शेतात झालेला प्रत्यक्ष बदल",
    stories_sub: "ग्रेनवाईज एआय वापरून उत्पादन वाढवणाऱ्या शेतकऱ्यांचे अनुभव.",
    faq_title: "वारंवार विचारले जाणारे प्रश्न",
    footer_hero_title: "एका लहान बियाण्यापासून ते",
    footer_hero_gold: "भरघोस पिकापर्यंत",
    footer_hero_sub: "ताजे बाजारभाव आणि पीक आरोग्यासाठी ग्रेनवाईज एआय वापरणाऱ्या हजारो शेतकऱ्यांशी जोडा.",
    footer_certified: "प्रमाणित ॲग्रीटेक प्लॅटफॉर्म · ISO 27001 सुरक्षित",
    footer_rights: "सर्व हक्क राखीव. शेतकऱ्यांच्या सेवेसाठी समर्पित",
    modal_title: "ग्रेनवाईज एआय डाउनलोड करा",
    modal_pre_register: "ॲंड्रॉइड पूर्व-नोंदणी (मोफत १४ दिवसांचा ट्रायल पॅक)",
    modal_scan_qr: "QR कोड स्कॅन करा",
    modal_feedback_tab: "अभिप्राय अपडेट करा"
  },

  Gujarati: {
    nav_features: "વિશેષતાઓ",
    nav_ai_scan: "એઆઈ સ્કેન",
    nav_npk_calc: "એનપીકે કેલ્ક્યુલેટર",
    nav_ananya_ai: "અનન્યા એઆઈ",
    nav_mandi: "બજાર ભાવ અને હવામાન",
    nav_farmer_stories: "ખેડૂત વાર્તાઓ",
    nav_faq: "પ્રશ્નોત્તરી",
    nav_download_app: "એપ ડાઉનલોડ કરો",
    nav_smart_farming: "સ્માર્ટ કૃષિ ઇન્ટેલિજન્સ",
    google_sign_in: "ગૂગલ સાઇન ઇન",
    made_in_india: "મેડ ઇન ઇન્ડિયા",
    hero_pill: "ગ્રેનવાઇઝ એઆઈ 🌾 · નેક્સ્ટ-જેન ચોક્કસ ખેતી",
    hero_welcome: "સ્વાગત છે",
    hero_brand: "ગ્રેનવાઇઝ એઆઈ માં! 🌾",
    hero_subtitle: "સ્માર્ટ ખેતી સાચી માહિતી સાથે શરૂ થાય છે. પાકના રોગોનું ત્વરિત નિદાન, લાઈવ બજાર ભાવ અને તમારી ભાષામાં 24/7 અનન્યા એઆઈ માર્ગદર્શન મેળવવા આજે જ એપ ડાઉનલોડ કરો.",
    hero_cta_download: "ડાઉનલોડ કરો અને ઉત્પાદન વધારો",
    hero_cta_google: "ગૂગલ સાથે સાઇન ઇન કરો",
    hero_cta_scan: "એઆઈ પાક તપાસ",
    hero_metric_langs: "22 ભારતીય ભાષાઓ",
    hero_metric_accuracy: "98.4% સચોટ નિદાન",
    hero_metric_support: "24/7 અનન્યા એઆઈ સહાય",
    hero_preview_title: "લાઈવ એઆઈ નિદાન પૂર્વાવલોકન",
    hero_preview_cam: "કેમેરા એઆઈ",
    hero_preview_cam_sub: "પાંદડાના સ્કેનથી ત્વરિત નિદાન",
    hero_preview_ananya_sub: "22 પ્રાદેશિક ભાષાઓ",
    core_pillar_badge: "ગ્રેનવાઇઝ એઆઈ ના 3 મુખ્ય સ્તંભો",
    core_title: "તમારા ખેતરોને સમૃદ્ધ બનાવવા માટે",
    core_thrive: "તૈયાર કરાયેલ",
    core_subtitle: "ત્વરિત પાક રોગ નિદાનથી લઈને બહુભાષી એઆઈ સલાહ સુધી, ગ્રેનવાઇઝ એઆઈ નિષ્ણાત ખેતી ટેકનોલોજી તમારા હાથમાં આપે છે.",
    core_explore: "વિશેષતાઓ જુઓ",
    indigenous_badge: "100% સ્વદેશી એઆઈ",
    atmanirbhar_title: "ભારતીય ખેડૂતો માટે ગર્વથી મેડ ઇન ઇન્ડિયા",
    atmanirbhar_desc: "ખાસ કરીને ભારતીય જમીન અને 22 ભાષાઓ માટે વિકસાવેલ.",
    empower_title: "ભારતના દરેક ખેડૂતને સશક્ત બનાવવું",
    empower_sub: "દરેક પાક અને ઋતુ માટે બનાવવામાં આવેલ આધુનિક ટેકનોલોજી.",
    diag_title: "કેમેરા આધારિત એઆઈ પાક નિદાન",
    diag_sub: "રોગગ્રસ્ત પાંદડા પર ફોન કેમેરો રાખો અને ત્વરિત એઆઈ નિદાન અને સારવાર મેળવો.",
    diag_upload_btn: "ફોટો અપલોડ કરો",
    diag_scan_btn: "એઆઈ સ્કેન શરૂ કરો",
    diag_analyzing: "પાકના સ્વાસ્થ્યની તપાસ થઈ રહી છે...",
    diag_result_title: "નિદાન અને ઉપચાર",
    npk_title: "સચોટ NPK ખાતર કેલ્ક્યુલેટર",
    npk_sub: "તમારા પાક, જમીન અને વિસ્તાર મુજબ ખાતરની સચોટ માત્રા ગણો.",
    npk_calc_btn: "ખાતરની માત્રા ગણો",
    ananya_title: "અનન્યા એઆઈ સહાયક",
    ananya_sub: "22 ભાષાઓમાં ખેતી સંબંધિત કોઈપણ પ્રશ્ન પૂછો.",
    ananya_placeholder: "તમારી ભાષામાં પ્રશ્ન લખો...",
    ananya_send: "પૂછો",
    mandi_title: "લાઈવ બજાર ભાવ અને MSP",
    mandi_sub: "ભારતના 2,500+ સરકારી માર્કેટ યાર્ડના તાજા ભાવ.",
    mandi_search_crop: "પાક શોધો (દા.ત. કપાસ, મગફળી, ઘઉં)",
    mandi_search_state: "રાજ્ય મુજબ ફિલ્ટર કરો",
    calendar_title: "પાક કેલેન્ડર અને સરકારી યોજનાઓ",
    calendar_sub: "મોસમી વાવેતર સલાહ અને સરકારી સહાયની માહિતી.",
    stories_title: "ભારતીય ખેતરો પર વાસ્તવિક અસર",
    stories_sub: "ગ્રેનવાઇઝ એઆઈ નો ઉપયોગ કરીને ઉત્પાદન વધારનાર ખેડૂતોના અનુભવો.",
    faq_title: "વારંવાર પૂછાતા પ્રશ્નો",
    footer_hero_title: "એક નાના બીજથી લઈને",
    footer_hero_gold: "વિપુલ પાક સુધી",
    footer_hero_sub: "તાજા બજાર ભાવ અને પાક નિદાન માટે ગ્રેનવાઇઝ એઆઈ વાપરતા હજારો ખેડૂતો સાથે જોડાઓ.",
    footer_certified: "પ્રમાણિત એગ્રીટેક પ્લેટફોર્મ · ISO 27001 સુરક્ષિત",
    footer_rights: "તમામ હકો અનામત. ખેડૂતો માટે પ્રેમથી બનાવેલ",
    modal_title: "ગ્રેનવાઇઝ એઆઈ ડાઉનલોડ કરો",
    modal_pre_register: "એન્ડ્રોઇડ પ્રી-રજીસ્ટર (મફત 14 દિવસનો ટ્રાયલ પેક)",
    modal_scan_qr: "QR કોડ સ્કેન કરો",
    modal_feedback_tab: "પ્રતિભાવ અપડેટ કરો"
  },

  Kannada: {
    nav_features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    nav_ai_scan: "AI ಸ್ಕ್ಯಾನ್",
    nav_npk_calc: "NPK ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    nav_ananya_ai: "ಅನನ್ಯ AI",
    nav_mandi: "ಮಾರುಕಟ್ಟೆ & ಹವಾಮಾನ",
    nav_farmer_stories: "ರೈತರ ಕಥೆಗಳು",
    nav_faq: "ಪ್ರಶ್ನೋತ್ತರ",
    nav_download_app: "ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    nav_smart_farming: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ",
    google_sign_in: "ಗೂಗಲ್ ಲಾಗಿನ್",
    made_in_india: "ಮೇಡ್ ಇನ್ ಇಂಡಿಯಾ",
    hero_pill: "GrainWise AI 🌾 · ಮುಂದಿನ ಪೀಳಿಗೆಯ ನಿಖರ ಕೃಷಿ",
    hero_welcome: "ಸ್ವಾಗತ",
    hero_brand: "GrainWise AI ಗೆ! 🌾",
    hero_subtitle: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿಯು ಸರಿಯಾದ ಮಾಹಿತಿಯೊಂದಿಗೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ. ಬೆಳೆ ರೋಗ ಪತ್ತೆ, ಲೈವ್ ಮಾರುಕಟ್ಟೆ ದರಗಳು ಮತ್ತು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ 24/7 ಅನನ್ಯ AI ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಇಂದೇ ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
    hero_cta_download: "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಇಳುವರಿ ಹೆಚ್ಚಿಸಿ",
    hero_cta_google: "ಗೂಗಲ್ ಲಾಗಿನ್ ಮಾಡಿ",
    hero_cta_scan: "AI ಬೆಳೆ ತಪಾಸಣೆ",
    hero_metric_langs: "22 ಭಾರತೀಯ ಭಾಷೆಗಳು",
    hero_metric_accuracy: "98.4% ನಿಖರ ಪತ್ತೆ",
    hero_metric_support: "24/7 ಅನನ್ಯ AI ಬೆಂಬಲ",
    hero_preview_title: "ಲೈವ್ AI ಪರೀಕ್ಷಾ ಮುನ್ನೋಟ",
    hero_preview_cam: "ಕ್ಯಾಮೆರಾ AI",
    hero_preview_cam_sub: "ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮೂಲಕ ತಕ್ಷಣದ ಪತ್ತೆ",
    hero_preview_ananya_sub: "22 ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳು",
    core_pillar_badge: "GrainWise AI ನ 3 ಪ್ರಮುಖ ಸ್ತಂಭಗಳು",
    core_title: "ನಿಮ್ಮ ಜಮೀನನ್ನು ಸಮೃದ್ಧಗೊಳಿಸಲು",
    core_thrive: "ರೂಪಿಸಲಾಗಿದೆ",
    core_subtitle: "ತಕ್ಷಣದ ಬೆಳೆ ರೋಗ ಪತ್ತೆಯಿಂದ ಹಿಡಿದು ಬಹುಭಾಷಾ AI ಸಲಹೆಯವರೆಗೆ, GrainWise AI ಆಧುನಿಕ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನವನ್ನು ನಿಮ್ಮ ಕೈಗೆ ನೀಡುತ್ತದೆ.",
    core_explore: "ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    indigenous_badge: "100% ಸ್ವದೇಶಿ AI",
    atmanirbhar_title: "ಭಾರತೀಯ ರೈತರಿಗಾಗಿ ಹೆಮ್ಮೆಯ ಮೇಡ್ ಇನ್ ಇಂಡಿಯಾ",
    atmanirbhar_desc: "ವಿಶೇಷವಾಗಿ ಭಾರತೀಯ ಮಣ್ಣು ಮತ್ತು 22 ಭಾಷೆಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
    empower_title: "ಭಾರತದ ಪ್ರತಿಯೊಬ್ಬ ರೈತನನ್ನೂ ಸಶಕ್ತಗೊಳಿಸುವುದು",
    empower_sub: "ಪ್ರತಿ ಬೆಳೆ ಮತ್ತು ಋತುವಿಗಾಗಿ ತಯಾರಿಸಿದ ಸುಧಾರಿತ ತಂತ್ರಜ್ಞಾನ.",
    diag_title: "ಕ್ಯಾಮೆರಾ ಆಧಾರಿತ AI ಬೆಳೆ ಪರೀಕ್ಷೆ",
    diag_sub: "ರೋಗಪೀಡಿತ ಎಲೆಯತ್ತ ಮೊಬೈಲ್ ಕ್ಯಾಮೆರಾ ಹಿಡಿದು ತಕ್ಷಣದ AI ಪತ್ತೆ ಮತ್ತು ಪರಿಹಾರ ಪಡೆಯಿರಿ.",
    diag_upload_btn: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    diag_scan_btn: "AI ಸ್ಕ್ಯಾನ್ ಪ್ರಾರಂಭಿಸಿ",
    diag_analyzing: "ಬೆಳೆಯ ಆರೋಗ್ಯ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    diag_result_title: "ರೋಗ ಪತ್ತೆ ಮತ್ತು ಪರಿಹಾರ",
    npk_title: "ನಿಖರ ಮಣ್ಣಿನ NPK ಗೊಬ್ಬರ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    npk_sub: "ನಿಮ್ಮ ಬೆಳೆ ಮತ್ತು ಮಣ್ಣಿನ ಪ್ರಕಾರಕ್ಕೆ ಅಗತ್ಯವಿರುವ ಗೊಬ್ಬರದ ಪ್ರಮಾಣವನ್ನು ಲೆಕ್ಕಹಾಕಿ.",
    npk_calc_btn: "ಗೊಬ್ಬರದ ಪ್ರಮಾಣ ಲೆಕ್ಕಹಾಕಿ",
    ananya_title: "ಅನನ್ಯ AI ಸಹಾಯಕ",
    ananya_sub: "22 ಭಾಷೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ.",
    ananya_placeholder: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಪ್ರಶ್ನೆ ಬರೆಯಿರಿ...",
    ananya_send: "ಕೇಳಿ",
    mandi_title: "ಲೈವ್ ಮಾರುಕಟ್ಟೆ ದರಗಳು & MSP",
    mandi_sub: "ಭಾರತದ 2,500+ ಸರ್ಕಾರಿ ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆಗಳ ಲೈವ್ ದರಗಳು.",
    mandi_search_crop: "ಬೆಳೆಯನ್ನು ಹುಡುಕಿ (ಉದಾ: ರಾಗಿ, ಭತ್ತ, ಹತ್ತಿ)",
    mandi_search_state: "ರಾಜ್ಯವಾರು ಹುಡುಕಿ",
    calendar_title: "ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್ ಮತ್ತು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    calendar_sub: "ಋತುಮಾನದ ಬಿತ್ತನೆ ಸಲಹೆಗಳು ಮತ್ತು ಸರ್ಕಾರಿ ಸಹಾಯಧನದ ಮಾಹಿತಿ.",
    stories_title: "ಭಾರತೀಯ ಜಮೀನುಗಳಲ್ಲಿ ನಿಜವಾದ ಬದಲಾವಣೆ",
    stories_sub: "GrainWise AI ಬಳಸಿ ಇಳುವರಿ ಹೆಚ್ಚಿಸಿಕೊಂಡ ರೈತರ ಅನುಭವಗಳು.",
    faq_title: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    footer_hero_title: "ಒಂದು ಸಣ್ಣ ಬೀಜದಿಂದ",
    footer_hero_gold: "ಸಮೃದ್ಧ ಬೆಳೆಯವರೆಗೆ",
    footer_hero_sub: "ಲೈವ್ ಮಾರುಕಟ್ಟೆ ದರಗಳು ಮತ್ತು ಬೆಳೆ ಪರೀಕ್ಷೆಗಾಗಿ GrainWise AI ಬಳಸುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ.",
    footer_certified: "ಪ್ರಮಾಣೀಕೃತ ಅಗ್ರಿಟೆಕ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ · ISO 27001 ಸುರಕ್ಷಿತ",
    footer_rights: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ರೈತರಿಗಾಗಿ ಪ್ರೀತಿಯಿಂದ ತಯಾರಿಸಲಾಗಿದೆ",
    modal_title: "GrainWise AI ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    modal_pre_register: "ಆಂಡ್ರಾಯ್ಡ್ ಮುಂಗಡ ನೋಂದಣಿ (ಉಚಿತ 14 ದಿನಗಳ ಟ್ರಯಲ್)",
    modal_scan_qr: "QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    modal_feedback_tab: "ಅಭಿಪ್ರಾಯ ನವೀಕರಿಸಿ"
  },

  Malayalam: {
    nav_features: "സവിശേഷതകൾ",
    nav_ai_scan: "AI സ്കാൻ",
    nav_npk_calc: "NPK കാൽക്കുലേറ്റർ",
    nav_ananya_ai: "അനന്യ AI",
    nav_mandi: "മാർക്കറ്റ് & കാലാവസ്ഥ",
    nav_farmer_stories: "കർഷക കഥകൾ",
    nav_faq: "ചോദ്യോത്തരങ്ങൾ",
    nav_download_app: "ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ",
    nav_smart_farming: "സ്മാർട്ട് കാർഷിക സാങ്കേതികവിദ്യ",
    google_sign_in: "ഗൂഗിൾ ലോഗിൻ",
    made_in_india: "മേഡ് ഇൻ ഇന്ത്യ",
    hero_pill: "GrainWise AI 🌾 · അടുത്ത തലമുറ കൃത്യതാ കൃഷി",
    hero_welcome: "സ്വാഗതം",
    hero_brand: "GrainWise AI-യിലേക്ക്! 🌾",
    hero_subtitle: "സ്മാർട്ട് കൃഷി കൃത്യമായ വിവരങ്ങളിൽ നിന്നാണ് ആരംഭിക്കുന്നത്. രോഗനിർണയം, മാർക്കറ്റ് വിലകൾ, നിങ്ങളുടെ മാതൃഭാഷയിൽ 24/7 അനന്യ AI സഹായം എന്നിവയ്ക്കായി ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ.",
    hero_cta_download: "ഡൗൺലോഡ് ചെയ്ത് മികച്ച വിളവ് നേടൂ",
    hero_cta_google: "ഗൂഗിൾ ലോഗിൻ",
    hero_cta_scan: "AI വിള പരിശോധന",
    hero_metric_langs: "22 ഇന്ത്യൻ ഭാഷകൾ",
    hero_metric_accuracy: "98.4% കൃത്യമായ രോഗനിർണയം",
    hero_metric_support: "24/7 അനന്യ AI സഹായം",
    hero_preview_title: "ലൈവ് AI രോഗനിർണയം",
    hero_preview_cam: "ക്യാമറ AI",
    hero_preview_cam_sub: "ഇല സ്കാൻ വഴി തൽക്ഷണ രോഗനിർണയം",
    hero_preview_ananya_sub: "22 പ്രാദേശിക ഭാഷകൾ",
    core_pillar_badge: "GrainWise AI-യുടെ 3 പ്രധാന തൂണുകൾ",
    core_title: "നിങ്ങളുടെ കൃഷിയിടങ്ങളെ സമൃദ്ധമാക്കാൻ",
    core_thrive: "രൂപകൽപ്പന ചെയ്തത്",
    core_subtitle: "തൽക്ഷണ രോഗനിർണയം മുതൽ ബഹുഭാഷാ AI ഉപദേശം വരെ, GrainWise AI അത്യാധുനിക സാങ്കേതികവിദ്യ നിങ്ങളുടെ കൈകളിൽ എത്തിക്കുന്നു.",
    core_explore: "സവിശേഷതകൾ കാണുക",
    indigenous_badge: "100% സ്വദേശി AI",
    atmanirbhar_title: "ഇന്ത്യൻ കർഷകർക്കായി അഭിമാനത്തോടെ മേഡ് ഇൻ ഇന്ത്യ",
    atmanirbhar_desc: "ഇന്ത്യൻ മണ്ണും 22 ഭാഷകളും ലക്ഷ്യമിട്ട് നിർമ്മിച്ചത്.",
    empower_title: "ഇന്ത്യയിലെ ഓരോ കർഷകനെയും ശാക്തീകരിക്കുന്നു",
    empower_sub: "ഓരോ വിളയ്ക്കും അനുയോജ്യമായ സാങ്കേതികവിദ്യ.",
    diag_title: "ക്യാമറ അധിഷ്ഠിത AI രോഗനിർണയം",
    diag_sub: "രോഗബാധിതമായ ഇലയിലേക്ക് ഫോൺ ക്യാമറ കാണിച്ച് തൽക്ഷണ ചികിത്സ നിർദ്ദേശങ്ങൾ നേടൂ.",
    diag_upload_btn: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യൂ",
    diag_scan_btn: "AI സ്കാൻ ആരംഭിക്കൂ",
    diag_analyzing: "വിളയുടെ ആരോഗ്യം പരിശോധിക്കുന്നു...",
    diag_result_title: "രോഗനിർണയവും പരിഹാരങ്ങളും",
    npk_title: "കൃത്യമായ NPK വള കാൽക്കുലേറ്റർ",
    npk_sub: "നിങ്ങളുടെ മണ്ണിലെ വളത്തിന്റെ അളവ് കൃത്യമായി കണക്കാക്കൂ.",
    npk_calc_btn: "വളത്തിന്റെ അളവ് കണക്കാക്കൂ",
    ananya_title: "അനന്യ AI അസിസ്റ്റന്റ്",
    ananya_sub: "22 ഭാഷകളിൽ കൃഷി ചോദ്യങ്ങൾ ചോദിക്കൂ.",
    ananya_placeholder: "നിങ്ങളുടെ ഭാഷയിൽ ചോദ്യം എഴുതൂ...",
    ananya_send: "ചോദിക്കൂ",
    mandi_title: "ലൈവ് മാർക്കറ്റ് നിരക്കുകൾ & MSP",
    mandi_sub: "ഇന്ത്യയിലെ 2,500+ വിപണികളിലെ തത്സമയ നിരക്കുകൾ.",
    mandi_search_crop: "വിള തിരയൂ (ഉദാ: നെല്ല്, നാളികേരം)",
    mandi_search_state: "സംസ്ഥാനം തിരഞ്ഞെടുക്കൂ",
    calendar_title: "വിള കലണ്ടറും സർക്കാർ പദ്ധതികളും",
    calendar_sub: "വിളവിറക്കൽ നിർദ്ദേശങ്ങളും സബ്‌സിഡി വിവരങ്ങളും.",
    stories_title: "കർഷകരുടെ അനുഭവങ്ങൾ",
    stories_sub: "GrainWise AI വഴി വിളവ് കൂട്ടിയ കർഷകരുടെ വാക്കുകൾ.",
    faq_title: "പതിവ് ചോദ്യങ്ങൾ",
    footer_hero_title: "ഒരു ചെറിയ വിത്തിൽ നിന്ന്",
    footer_hero_gold: "സമൃദ്ധമായ വിളവെടുപ്പ് വരെ",
    footer_hero_sub: "മാർക്കറ്റ് വിലകൾക്കും രോഗനിർണയത്തിനുമായി GrainWise AI ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് കർഷകർക്കൊപ്പം ചേരൂ.",
    footer_certified: "അംഗീകൃത അഗ്രിടെക് പ്ലാറ്റ്‌ഫോം · ISO 27001 സുരക്ഷിതം",
    footer_rights: "എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം. കർഷകർക്കായി സ്നേഹത്തോടെ നിർമ്മിച്ചത്",
    modal_title: "GrainWise AI ഡൗൺലോഡ് ചെയ്യൂ",
    modal_pre_register: "ആൻഡ്രോയിഡ് മുൻകൂർ രജിസ്ട്രേഷൻ (സൗജന്യ 14 ദിവസ ട്രയൽ)",
    modal_scan_qr: "QR കോഡ് സ്കാൻ ചെയ്യൂ",
    modal_feedback_tab: "അഭിപ്രായം അറിയിക്കൂ"
  },

  Odia: {
    nav_features: "ବିଶେଷତା",
    nav_ai_scan: "AI ସ୍କାନ୍",
    nav_npk_calc: "NPK କାଲକୁଲେଟର",
    nav_ananya_ai: "ଅନନ୍ୟା AI",
    nav_mandi: "ମଣ୍ଡି ଓ ପାଣିପାଗ",
    nav_farmer_stories: "କୃଷକ କାହାଣୀ",
    nav_faq: "ପ୍ରଶ୍ନୋତ୍ତର",
    nav_download_app: "ଆପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    nav_smart_farming: "ସ୍ମାର୍ଟ କୃଷି ଜ୍ଞାନକୌଶଳ",
    google_sign_in: "ଗୁଗଲ୍ ସାଇନ୍ ଇନ୍",
    made_in_india: "ମେଡ୍ ଇନ୍ ଇଣ୍ଡିଆ",
    hero_pill: "ଗ୍ରେନୱାଇଜ୍ AI 🌾 · ଆଧୁନିକ ସଠିକ୍ କୃଷି",
    hero_welcome: "ସ୍ୱାଗତମ",
    hero_brand: "ଗ୍ରେନୱାଇଜ୍ AI କୁ! 🌾",
    hero_subtitle: "ସ୍ମାର୍ଟ କୃଷି ସଠିକ୍ ସୂଚନାରୁ ଆରମ୍ଭ ହୁଏ। ରୋଗ ନିରୂପଣ, ଲାଇଭ୍ ମଣ୍ଡି ଦର ଏବଂ ନିଜ ଭାଷାରେ ୨୪/୭ ଅନନ୍ୟା AI ପରାମର୍ଶ ପାଇଁ ଆଜି ହିଁ ଆପ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ।",
    hero_cta_download: "ଡାଉନଲୋଡ୍ କରନ୍ତୁ ଓ ଅମଳ ବୃଦ୍ଧି କରନ୍ତୁ",
    hero_cta_google: "ଗୁଗଲ୍ ସାଇନ୍ ଇନ୍",
    hero_cta_scan: "AI ଫସଲ ସ୍କାନ୍",
    hero_metric_langs: "୨୨ଟି ଭାରତୀୟ ଭାଷା",
    hero_metric_accuracy: "୯୮.୪% ସଠିକ୍ ନିରୂପଣ",
    hero_metric_support: "୨୪/୭ ଅନନ୍ୟା AI ସହାୟତା",
    hero_preview_title: "ଲାଇଭ୍ AI ନିରୂପଣ ପୂର୍ବାବଲୋକନ",
    hero_preview_cam: "କ୍ୟାମେରା AI",
    hero_preview_cam_sub: "ପତ୍ର ସ୍କାନରୁ ତୁରନ୍ତ ରୋଗ ନିରୂପଣ",
    hero_preview_ananya_sub: "୨୨ଟି ଆଞ୍ଚଳିକ ଭାଷା",
    core_pillar_badge: "ଗ୍ରେନୱାଇଜ୍ AI ର ୩ଟି ମୁଖ୍ୟ ସ୍ତମ୍ଭ",
    core_title: "ଆପଣଙ୍କ କ୍ଷେତକୁ ସମୃଦ୍ଧ କରିବା ପାଇଁ",
    core_thrive: "ନିର୍ମିତ",
    core_subtitle: "ତୁରନ୍ତ ରୋଗ ନିରୂପଣରୁ ବହୁଭାଷୀ AI ପରାମର୍ଶ ପର୍ଯ୍ୟନ୍ତ, ଗ୍ରେନୱାଇଜ୍ AI ଆପଣଙ୍କ ହାତରେ ସମସ୍ତ କୃଷି ପ୍ରଯୁକ୍ତି ପହଞ୍ଚାଏ।",
    core_explore: "ବିଶେଷତା ଦେଖନ୍ତୁ",
    indigenous_badge: "୧୦୦% ସ୍ୱଦେଶୀ AI",
    atmanirbhar_title: "ଭାରତୀୟ କୃଷକଙ୍କ ପାଇଁ ଗର୍ବର ସହ ମେଡ୍ ଇନ୍ ଇଣ୍ଡିଆ",
    atmanirbhar_desc: "ବିଶେଷ ଭାବରେ ଭାରତୀୟ ମାଟି ଏବଂ ୨୨ଟି ଭାଷା ପାଇଁ ପ୍ରସ୍ତୁତ।",
    empower_title: "ଭାରତର ପ୍ରତ୍ୟେକ କୃଷକଙ୍କୁ ସଶକ୍ତ କରିବା",
    empower_sub: "ପ୍ରତ୍ୟେକ ଫସଲ ଏବଂ ଋତୁ ପାଇଁ ନିର୍ମିତ ଆଧୁନିକ ପ୍ରଯୁକ୍ତିବିଦ୍ୟା।",
    diag_title: "କ୍ୟାମେରା ଆଧାରିତ AI ଫସଲ ରୋଗ ନିରୂପଣ",
    diag_sub: "ରୋଗାକ୍ରାନ୍ତ ପତ୍ର ଉପରେ ଫୋନ୍ କ୍ୟାମେରା ରଖି ତୁରନ୍ତ ନିରୂପଣ ଓ ପ୍ରତିକାର ପାଆନ୍ତୁ।",
    diag_upload_btn: "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
    diag_scan_btn: "AI ସ୍କାନ୍ ଆରମ୍ଭ କରନ୍ତୁ",
    diag_analyzing: "ଫସଲର ସ୍ୱାସ୍ଥ୍ୟ ପରୀକ୍ଷା କରାଯାଉଛି...",
    diag_result_title: "ନିରୂପଣ ଓ ପ୍ରତିକାର",
    npk_title: "ସଠିକ୍ NPK ଖତ କାଲକୁଲେଟର",
    npk_sub: "ଆପଣଙ୍କ ଫସଲ ଏବଂ ଜମିର ଆକାର ଅନୁସାରେ ଖତର ପରିମାଣ ଗଣନା କରନ୍ତୁ।",
    npk_calc_btn: "ଖତର ପରିମାଣ ଗଣନା କରନ୍ତୁ",
    ananya_title: "ଅନନ୍ୟା AI ସହାୟକ",
    ananya_sub: "୨୨ଟି ଭାଷାରେ କୃଷି ସମ୍ବନ୍ଧୀୟ ଯେକୌଣସି ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ।",
    ananya_placeholder: "ନିଜ ଭାଷାରେ ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ...",
    ananya_send: "ପଚାରନ୍ତୁ",
    mandi_title: "ଲାଇଭ୍ ମଣ୍ଡି ଦର ଓ MSP",
    mandi_sub: "ଭାରତର ୨,୫୦୦+ ସରକାରୀ ମଣ୍ଡିରୁ ତାଜା ଦର।",
    mandi_search_crop: "ଫସଲ ଖୋଜନ୍ତୁ (ଯେପରି ଧାନ, ଗହମ)",
    mandi_search_state: "ରାଜ୍ୟ ଅନୁସାରେ ଫିଲ୍ଟର୍ କରନ୍ତୁ",
    calendar_title: "ଫସଲ କ୍ୟାଲେଣ୍ଡର ଓ ସରକାରୀ ଯୋଜନା",
    calendar_sub: "ଋତୁକାଳୀନ ଚାଷ ପରାମର୍ଶ ଏବଂ ସରକାରୀ ସବସିଡି ସୂଚନା।",
    stories_title: "ଜମିରେ ବାସ୍ତବ ପରିବର୍ତ୍ତନ",
    stories_sub: "ଗ୍ରେନୱାଇଜ୍ AI ବ୍ୟବହାର କରି ଅମଳ ବଢ଼ାଇଥିବା ଚାଷୀଙ୍କ ଅନୁଭୂତି।",
    faq_title: "ସାଧାରଣ ପ୍ରଶ୍ନୋତ୍ତର",
    footer_hero_title: "ଗୋଟିଏ ଛୋଟ ମଞ୍ଜିରୁ",
    footer_hero_gold: "ପ୍ରଚୁର ଅମଳ ପର୍ଯ୍ୟନ୍ତ",
    footer_hero_sub: "ତାଜା ମଣ୍ଡି ଦର ଏବଂ ଫସଲ ସ୍ୱାସ୍ଥ୍ୟ ପାଇଁ ଗ୍ରେନୱାଇଜ୍ AI ବ୍ୟବହାର କରୁଥିବା ହଜାର ହଜାର ଚାଷୀଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ।",
    footer_certified: "ପ୍ରମାଣିତ ଆଗ୍ରିଟେକ୍ ପ୍ଲାଟଫର୍ମ · ISO 27001 ସୁରକ୍ଷିତ",
    footer_rights: "ସର୍ବସତ୍ତ୍ୱ ସଂରକ୍ଷିତ। କୃଷକଙ୍କ ପାଇଁ ଶ୍ରଦ୍ଧାର ସହ ନିର୍ମିତ",
    modal_title: "ଗ୍ରେନୱାଇଜ୍ AI ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    modal_pre_register: "ଆଣ୍ଡ୍ରଏଡ୍ ପ୍ରାକ୍-ପଞ୍ଜୀକରଣ (ମାଗଣା ୧୪ ଦିନର ଟ୍ରାଏଲ୍)",
    modal_scan_qr: "QR କୋଡ୍ ସ୍କାନ୍ କରନ୍ତୁ",
    modal_feedback_tab: "ମତାମତ ଅପଡେଟ୍ କରନ୍ତୁ"
  },

  Assamese: {
    nav_features: "বৈশিষ্ট্যসমূহ",
    nav_ai_scan: "AI স্কেন",
    nav_npk_calc: "NPK কেলকুলেটৰ",
    nav_ananya_ai: "অনন্যা AI",
    nav_mandi: "বজাৰ দৰ আৰু বতৰ",
    nav_farmer_stories: "কৃষকৰ কাহিনী",
    nav_faq: "প্রশ্নোত্তৰ",
    nav_download_app: "অ্যাপ ডাউনলোড কৰক",
    nav_smart_farming: "স্মাৰ্ট কৃষি প্ৰযুক্তি",
    google_sign_in: "গুগল চাইন ইন",
    made_in_india: "মেড ইন ইণ্ডিয়া",
    hero_pill: "গ্ৰেইনৱাইজ AI 🌾 · উন্নত মানৰ নিখুঁত কৃষি",
    hero_welcome: "স্বাগতম",
    hero_brand: "গ্ৰেইনৱাইজ AI লৈ! 🌾",
    hero_subtitle: "স্মাৰ্ট কৃষি সঠিক তথ্যৰে আৰম্ভ হয়। শস্যৰ ৰোগ চিনাক্তকৰণ, লাইভ বজাৰ দৰ আৰু নিজৰ ভাষাত ২৪/৭ অনন্যা AI পৰামৰ্শ লাভ কৰিবলৈ আজিয়েই অ্যাপ ডাউনলোড কৰক।",
    hero_cta_download: "ডাউনলোড কৰক আৰু উৎপাদন বৃদ্ধি কৰক",
    hero_cta_google: "গুগলৰে চাইন ইন কৰক",
    hero_cta_scan: "AI শস্য পৰীক্ষা",
    hero_metric_langs: "২২ টা ভাৰতীয় ভাষা",
    hero_metric_accuracy: "৯৮.৪% শুদ্ধ ৰোগ নিৰ্ণয়",
    hero_metric_support: "২৪/৭ অনন্যা AI সহায়",
    hero_preview_title: "লাইভ AI পৰীক্ষা পূৰ্বদৰ্শন",
    hero_preview_cam: "কেমেৰা AI",
    hero_preview_cam_sub: "পাত স্কেন কৰি লগে লগে ৰোগ নিৰ্ণয়",
    hero_preview_ananya_sub: "২২ টা আঞ্চলিক ভাষা",
    core_pillar_badge: "গ্ৰেইনৱাইজ AI ৰ ৩ টা মূল স্তম্ভ",
    core_title: "আপোনাৰ পথাৰ সমৃদ্ধ কৰিবলৈ",
    core_thrive: "বিশেষভাৱে প্ৰস্তুত",
    core_subtitle: "লগে লগে ৰোগ চিনাক্তকৰণৰ পৰা আৰম্ভ কৰি বহুভাষিক AI পৰামৰ্শলৈকে, গ্ৰেইনৱাইজ AI এ উন্নত কৃষি প্ৰযুক্তি আপোনাৰ হাতত তুলি দিয়ে।",
    core_explore: "বৈশিষ্ট্যসমূহ চাওক",
    indigenous_badge: "১০০% থলুৱা AI",
    atmanirbhar_title: "ভাৰতীয় কৃষকসকলৰ বাবে গৌৰৱেৰে মেড ইন ইণ্ডিয়া",
    atmanirbhar_desc: "বিশেষভাৱে ভাৰতীয় মাটি আৰু ২২ টা ভাষাৰ বাবে নিৰ্মিত।",
    empower_title: "ভাৰতৰ প্ৰতিগৰাকী কৃষকক সশক্ত কৰা",
    empower_sub: "প্ৰতিটো শস্য আৰু ঋতুৰ বাবে তৈয়াৰ কৰা আধুনিক প্ৰযুক্তি।",
    diag_title: "কেমেৰা ভিত্তিক AI শস্য ৰোগ নিৰ্ণয়",
    diag_sub: "আক্ৰান্ত পাতত ফোন কেমেৰা ৰাখক আৰু লগে লগে AI নিৰ্ণয় আৰু প্ৰতিকাৰ পাওক।",
    diag_upload_btn: "ফটো আপলোড কৰক",
    diag_scan_btn: "AI স্কেন আৰম্ভ কৰক",
    diag_analyzing: "শস্যৰ স্বাস্থ্য পৰীক্ষা কৰা হৈছে...",
    diag_result_title: "ৰোগ নিৰ্ণয় আৰু সমাধান",
    npk_title: "সঠিক NPK সাৰ কেলকুলেটৰ",
    npk_sub: "আপোনাৰ শস্য আৰু মাটিৰ জোখ অনুসৰি সাৰৰ সঠিক পৰিমাণ গণনা কৰক।",
    npk_calc_btn: "সাৰৰ পৰিমাণ গণনা কৰক",
    ananya_title: "অনন্যা AI সহায়ক",
    ananya_sub: "২২ টা ভাষাত কৃষি সংক্ৰান্তীয় যিকোনো প্ৰশ্ন সোধক।",
    ananya_placeholder: "আপোনাৰ ভাষাত প্ৰশ্ন লিখক...",
    ananya_send: "সোধক",
    mandi_title: "লাইভ বজাৰ দৰ আৰু MSP",
    mandi_sub: "ভাৰতৰ ২,৫০০+ চৰকাৰী বজাৰৰ পৰা শস্যৰ সজাতীয় দৰ।",
    mandi_search_crop: "শস্য বিচাৰক (যেনে ধান, ঘেঁহু)",
    mandi_search_state: "ৰাজ্য অনুসৰি বাছনি কৰক",
    calendar_title: "শস্য কেলণ্ডাৰ আৰু চৰকাৰী আঁচনি",
    calendar_sub: "ঋতুভিত্তিক খেতিৰ পৰামৰ্শ আৰু চৰকাৰী ৰেহাইৰ তথ্য।",
    stories_title: "পথাৰত প্ৰত্যক্ষ প্ৰভাৱ",
    stories_sub: "গ্ৰেইনৱাইজ AI ব্যৱহাৰ কৰি উৎপাদন বৃদ্ধি কৰা কৃষকসকলৰ অভিজ্ঞতা।",
    faq_title: "সঘনাই সোধা প্ৰশ্নসমূহ",
    footer_hero_title: "এটা সৰু গুটিৰ পৰা",
    footer_hero_gold: "প্ৰচুৰ ফচললৈকে",
    footer_hero_sub: "বজাৰ দৰ আৰু শস্য পৰীক্ষাৰ বাবে গ্ৰেইনৱাইজ AI ব্যৱহাৰ কৰা হাজাৰ হাজাৰ কৃষকৰ সৈতে যুক্ত হওক।",
    footer_certified: "স্বীকৃত এগ্ৰিটেক প্লেটফৰ্ম · ISO 27001 সুৰক্ষিত",
    footer_rights: "সকলো অধিকাৰ সংৰক্ষিত। কৃষকসকলৰ বাবে শ্ৰদ্ধাৰে নিৰ্মিত",
    modal_title: "গ্ৰেইনৱাইজ AI ডাউনলোড কৰক",
    modal_pre_register: "এণ্ড্ৰইড পূৰ্ব-পঞ্জীয়ন (বিনামূলীয়া ১৪ দিনৰ ট্ৰায়েল)",
    modal_scan_qr: "QR ক'ড স্কেন কৰক",
    modal_feedback_tab: "মতামত নবীকৰণ কৰক"
  },

  Urdu: {
    nav_features: "خصوصیات",
    nav_ai_scan: "اے آئی اسکین",
    nav_npk_calc: "این پی کے کیلکولیٹر",
    nav_ananya_ai: "اننیا اے آئی",
    nav_mandi: "منڈی اور موسم",
    nav_farmer_stories: "کسانوں کی کہانیاں",
    nav_faq: "سوال و جواب",
    nav_download_app: "ایپ ڈاؤن لوڈ کریں",
    nav_smart_farming: "اسمارٹ زرعی ذہانت",
    google_sign_in: "گوگل سے سائن ان کریں",
    made_in_india: "میڈ ان انڈیا",
    hero_pill: "گرین وائز اے آئی 🌾 · اگلی نسل کی جدید زراعت",
    hero_welcome: "خوش آمدید",
    hero_brand: "گرین وائز اے آئی میں! 🌾",
    hero_subtitle: "اسمارٹ زراعت درست معلومات سے شروع ہوتی ہے۔ اپنی فصلوں کی بیماریوں کی فوری تشخیص، منڈی کے تازہ ترین بھاؤ اور اپنی زبان میں 24/7 اننیا اے آئی کی رہنمائی حاصل کریں۔",
    hero_cta_download: "ڈاؤن لوڈ کریں اور پیداوار بڑھائیں",
    hero_cta_google: "گوگل سائن ان",
    hero_cta_scan: "اے آئی فصل جانچ",
    hero_metric_langs: "22 ہندوستانی زبانیں",
    hero_metric_accuracy: "98.4% درست تشخیص",
    hero_metric_support: "24/7 اننیا اے آئی مدد",
    hero_preview_title: "لائیو اے آئی تشخیص کا منظر نامہ",
    hero_preview_cam: "کیمرہ اے آئی",
    hero_preview_cam_sub: "پتے کی اسکین سے فوری تشخیص",
    hero_preview_ananya_sub: "22 علاقائی زبانیں",
    core_pillar_badge: "گرین وائز اے آئی کے 3 بنیادی ستون",
    core_title: "آپ کے کھیتوں کی خوشحالی کے لیے",
    core_thrive: "خاص طور پر تیار کردہ",
    core_subtitle: "فصل کی فوری تشخیص سے لے کر کثیر لسانی اے آئی مشورے تک، گرین وائز اے آئی جدید زرعی ٹیکنالوجی آپ کی ہتھلی پر لاتا ہے۔",
    core_explore: "خصوصیات دیکھیں",
    indigenous_badge: "100% دیسی اے آئی",
    atmanirbhar_title: "ہندوستانی کسانوں کے لیے فخر سے میڈ ان انڈیا",
    atmanirbhar_desc: "خاص طور پر ہندوستانی مٹی، 22 زبانوں اور مقامی منڈی کے لیے تیار کردہ۔",
    empower_title: "ہندوستان کے ہر کسان کو بااختیار بنانا",
    empower_sub: "ہر فصل اور موسم کے لیے تیار کی گئی جدید ٹیکنالوجی۔",
    diag_title: "کیمرہ پر مبنی اے آئی فصل کی تشخیص",
    diag_sub: "متاثرہ پتے پر فون کا کیمرہ رکھیں اور فوری اے آئی تشخیص اور علاج حاصل کریں۔",
    diag_upload_btn: "تصویر اپ لوڈ کریں",
    diag_scan_btn: "اے آئی اسکین شروع کریں",
    diag_analyzing: "فصل کی صحت کی جانچ کی جا رہی ہے...",
    diag_result_title: "تشخیص اور علاج",
    npk_title: "درست این پی کے کھاد کیلکولیٹر",
    npk_sub: "اپنی فصل اور مٹی کے مطابق کھاد کی درست مقدار کا حساب لگائیں۔",
    npk_calc_btn: "کھاد کی مقدار معلوم کریں",
    ananya_title: "اننیا اے آئی معاون",
    ananya_sub: "22 زبانوں میں زراعت سے متعلق کوئی بھی سوال پوچھیں۔",
    ananya_placeholder: "اپنی زبان میں سوال لکھیں...",
    ananya_send: "پوچھیں",
    mandi_title: "لائیو منڈی بھاؤ اور ایم ایس پی",
    mandi_sub: "ہندوستان کی 2,500+ سرکاری منڈیوں کے تازہ ترین بھاؤ۔",
    mandi_search_crop: "فصل تلاش کریں (مثلاً گندم، چاول)",
    mandi_search_state: "ریاست کے لحاظ سے منتخب کریں",
    calendar_title: "فصل کا کیلنڈر اور سرکاری اسکیمیں",
    calendar_sub: "موسمی کاشت کاری کے مشورے اور سرکاری سبسڈی کی معلومات۔",
    stories_title: "کھیتوں پر حقیقی تبدیلی",
    stories_sub: "ان کسانوں کے تجربات جنہوں نے گرین وائز اے آئی کے ذریعے پیداوار بڑھائی۔",
    faq_title: "عام طور پر پوچھے جانے والے سوالات",
    footer_hero_title: "ایک چھوٹے سے بیج سے لے کر",
    footer_hero_gold: "شاندار فصل تک",
    footer_hero_sub: "تازہ منڈی بھاؤ اور فصل کی جانچ کے لیے گرین وائز اے آئی استعمال کرنے والے ہزاروں کسانوں کے ساتھ جڑیں۔",
    footer_certified: "تصدیق شدہ ایگری ٹیک پلیٹ فارم · ISO 27001 محفوظ",
    footer_rights: "جملہ حقوق محفوظ ہیں۔ کسانوں کے لیے محبت سے تیار کردہ",
    modal_title: "گرین وائز اے آئی ڈاؤن لوڈ کریں",
    modal_pre_register: "اینڈرائیڈ پری رجسٹریشن (مفت 14 دن کا ٹرائل)",
    modal_scan_qr: "کیو آر کوڈ اسکین کریں",
    modal_feedback_tab: "رائے کی تجدید کریں"
  }
};

// Fallback logic for languages sharing scripts or matching closely
export function getTranslation(lang, key) {
  const selectedObj = TRANSLATIONS[lang] || TRANSLATIONS.Hindi || TRANSLATIONS.English;
  if (selectedObj && selectedObj[key]) {
    return selectedObj[key];
  }
  // Fallback to Hindi if not present in selected lang, then English
  return TRANSLATIONS.Hindi[key] || TRANSLATIONS.English[key] || key;
}

/**
 * React Context Provider for Global Language Management
 */
const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [selectedLang, setSelectedLang] = useState('English');

  const t = (key) => getTranslation(selectedLang, key);

  return (
    <LanguageContext.Provider value={{ selectedLang, setSelectedLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
